---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statful-k8s-metrics-collector
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: k8s-metrics-collector
  name: k8s-metrics-collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s-metrics-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: k8s-metrics-collector
    spec:
      serviceAccountName: statful-k8s-metrics-collector
      containers:
        - image: statful/k8s-metrics-collector:1.1.0
          imagePullPolicy: Always
          name: k8s-metrics-collector
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.5
              memory: 320Mi